# Generated by Django 3.0 on 2019-12-04 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(null=True)),
                ('has_projector', models.BooleanField()),
                ('has_whiteboard', models.BooleanField()),
                ('volume', models.IntegerField(null=True)),
                ('has_air_conditioning', models.BooleanField()),
                ('has_noise_isolation', models.BooleanField()),
                ('computer_count', models.IntegerField()),
                ('micro_count', models.IntegerField()),
                ('has_internet', models.BooleanField()),
                ('has_speakers', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField()),
                ('time_till', models.DateTimeField()),
                ('capacity', models.IntegerField(null=True)),
                ('computer_count', models.IntegerField(null=True)),
                ('micro_count', models.IntegerField(null=True)),
                ('has_projector', models.BooleanField(null=True)),
                ('has_whiteboard', models.BooleanField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('has_air_conditioning', models.BooleanField(null=True)),
                ('has_noise_isolation', models.BooleanField(null=True)),
                ('has_internet', models.BooleanField(null=True)),
                ('has_speakers', models.BooleanField(null=True)),
                ('capacity_coef', models.FloatField(null=True)),
                ('has_projector_coef', models.FloatField(null=True)),
                ('has_whiteboard_coef', models.FloatField(null=True)),
                ('volume_coef', models.FloatField(null=True)),
                ('has_air_conditioning_coef', models.FloatField(null=True)),
                ('has_noise_isolation_coef', models.FloatField(null=True)),
                ('computer_count_coef', models.FloatField(null=True)),
                ('micro_count_coef', models.FloatField(null=True)),
                ('has_internet_coef', models.FloatField(null=True)),
                ('has_speakers_coef', models.FloatField(null=True)),
                ('edge_weight', models.FloatField(null=True)),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditory.Auditory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
