# Generated by Django 3.0 on 2019-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(null=True)),
                ('has_projector', models.BooleanField()),
                ('has_whiteboard', models.BooleanField()),
                ('volume', models.IntegerField(null=True)),
                ('has_air_conditioning', models.BooleanField()),
                ('has_noise_isolation', models.BooleanField()),
                ('computer_count', models.IntegerField()),
                ('micro_count', models.IntegerField()),
                ('has_internet', models.BooleanField()),
                ('has_speakers', models.BooleanField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
