# Generated by Django 3.0 on 2019-12-05 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='auditory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auditory.Auditory'),
        ),
    ]
